# Generated by Django 5.2.4 on 2025-07-29 18:54

import imageupload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=imageupload.models.unique_file_path),
        ),
    ]
