# Generated by Django 5.2.4 on 2025-07-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Retention period in days (max 30). Null means unlimited for admins.', null=True),
        ),
    ]
