# Generated by Django 5.2.4 on 2025-08-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GamingBaeren.de', max_length=100)),
                ('light_bg_color', models.CharField(default='#f5f0e9', help_text='Hex color for light mode background', max_length=7)),
                ('light_text_color', models.CharField(default='#000000', help_text='Hex color for light mode text', max_length=7)),
                ('dark_bg_color', models.CharField(default='#000000', help_text='Hex color for dark mode background', max_length=7)),
                ('dark_text_color', models.CharField(default='#d1d5db', help_text='Hex color for dark mode text', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
