# Generated by Django 5.2.4 on 2025-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dark_footer_bg_color',
            field=models.CharField(default='#111827', help_text='Hex color for dark mode footer background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_footer_text_color',
            field=models.CharField(default='#f9fafb', help_text='Hex color for dark mode footer text', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_navbar_bg_color',
            field=models.CharField(default='#111827', help_text='Hex color for dark mode navbar background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_navbar_text_color',
            field=models.CharField(default='#f9fafb', help_text='Hex color for dark mode navbar text', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='light_footer_bg_color',
            field=models.CharField(default='#f9fafb', help_text='Hex color for light mode footer background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='light_footer_text_color',
            field=models.CharField(default='#1f2937', help_text='Hex color for light mode footer text', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='light_navbar_bg_color',
            field=models.CharField(default='#1f2937', help_text='Hex color for light mode navbar background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='light_navbar_text_color',
            field=models.CharField(default='#d1d5db', help_text='Hex color for light mode navbar text', max_length=7),
        ),
    ]
